In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from google.colab import files
uploaded = files.upload()

Saving student_dropout_dataset_v3.csv to student_dropout_dataset_v3.csv

In [5]:
df = pd.read_csv("student_dropout_dataset_v3.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             10000 non-null  int64
 1   Age                    10000 non-null  float64
 2   Gender                 10000 non-null  object
 3   Family_Income          9500 non-null   float64
 4   Internet_Access        10000 non-null  object
 5   Study_Hours_per_Day    9500 non-null   float64
 6   Attendance_Rate        10000 non-null  float64
 7   Assignment_Delay_Days  10000 non-null  int64
 8   Travel_Time_Minutes    10000 non-null  float64
 9   Part_Time_Job          10000 non-null  object
 10  Scholarship            10000 non-null  object
 11  Stress_Index           9500 non-null   float64
 12  GPA                    10000 non-null  float64
 13  Semester_GPA           10000 non-null  float64
 14  CGPA                   10000 non-null  float64
 15  Semester               10000 non-null  object
 16  Department             10000 non-null  object
 17  Parental_Education     9489 non-null   object
 18  Dropout                10000 non-null  int64
dtypes: float64(9), int64(3), object(7)
memory usage: 1.4+ MB

In [5]:
df.head()

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,1,22.1,Male,25000.0,Yes,3.36,86.1,2,20.4,Yes,No,5.5,0.96,0.90,0.90,Year 1,Arts,High School,0
1,2,20.7,Male,25000.0,Yes,4.30,68.0,2,44.0,No,No,6.8,1.28,1.20,1.19,Year 3,Engineering,Bachelor,1
2,3,22.4,Male,40183.0,Yes,4.40,70.9,0,48.9,Yes,No,5.5,1.68,1.32,1.32,Year 1,Arts,Master,0
3,4,24.4,Male,NaN,Yes,NaN,82.2,2,38.6,No,No,NaN,1.78,1.77,1.77,Year 1,CS,High School,1
4,5,20.5,Female,25319.0,Yes,4.19,75.7,1,23.0,No,No,7.0,1.48,0.91,0.87,Year 4,Business,Bachelor,0

In [6]:
df.describe()

,Student_ID,Age,Family_Income,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Stress_Index,GPA,Semester_GPA,CGPA,Dropout
count,10000.00000,10000.00000,9500.000000,9500.000000,10000.00000,10000.000000,10000.00000,9500.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,5000.50000,21.02606,38377.247474,4.014592,81.73683,1.799700,30.17926,5.507147,2.308440,2.300057,2.298761,0.23540
std,2886.89568,2.13981,20496.232179,1.295450,8.22093,1.344307,11.91887,1.765951,1.061717,1.074407,1.072555,0.42427
min,1.00000,17.00000,25000.000000,0.500000,38.20000,0.000000,5.00000,1.000000,0.000000,0.000000,0.000000,0.00000
25%,2500.75000,19.50000,25000.000000,3.160000,76.40000,1.000000,21.90000,4.300000,1.550000,1.520000,1.520000,0.00000
50%,5000.50000,21.00000,29740.500000,4.000000,81.80000,2.000000,30.20000,5.500000,2.350000,2.350000,2.350000,0.00000
75%,7500.25000,22.50000,44520.000000,4.870000,87.30000,3.000000,38.40000,6.700000,3.120000,3.150000,3.150000,0.00000
max,10000.00000,29.60000,316601.000000,8.980000,100.00000,8.000000,74.90000,10.000000,4.000000,4.000000,4.000000,1.00000

## ENCODING
Gender, Internet_Access, Part_Time_job, Scholarship,
Semester, Parental_Education, Department

In [8]:
numerical_col = df.select_dtypes(include=np.number).columns
print(type(numerical_col))
numerical_col = list(numerical_col)
print(type(numerical_col))
numerical_col = [col for col in numerical_col if col != "Student_ID" and col != "Dropout"]

<class 'pandas.core.indexes.base.Index'>
<class 'list'>

In [9]:
for col in numerical_col:
  print(f"{col}:-\n{df[col].skew()}\n")

Age:-
0.1832201742424678

Family_Income:-
2.82686234373061

Study_Hours_per_Day:-
0.03149394289422647

Attendance_Rate:-
-0.17201347706961656

Assignment_Delay_Days:-
0.7044039552251524

Travel_Time_Minutes:-
0.09410694533289736

Stress_Index:-
-0.007738731025494548

GPA:-
-0.19793724935171453

Semester_GPA:-
-0.2217484763410073

CGPA:-
-0.22493904217742858

## PowerTransform
Assingment_Delay_Days, Family_Income

In [6]:
df.drop(["Student_ID"], axis= 1,inplace = True)

In [7]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [15]:
df["Dropout"].value_counts()

Dropout
0    7646
1    2354
Name: count, dtype: int64

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
from sklearn.pipeline import Pipeline

In [10]:
base_model = LogisticRegression(
    solver="lbfgs",
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

In [11]:
from sklearn.compose import ColumnTransformer

In [39]:
df.isnull().sum()

Age                        0
Gender                     0
Family_Income            500
Internet_Access            0
Study_Hours_per_Day      500
Attendance_Rate            0
Assignment_Delay_Days      0
Travel_Time_Minutes        0
Part_Time_Job              0
Scholarship                0
Stress_Index             500
GPA                        0
Semester_GPA               0
CGPA                       0
Semester                   0
Department                 0
Parental_Education       511
Dropout                    0
dtype: int64

In [40]:
(df.isnull().sum()/len(df))*100

Age                      0.00
Gender                   0.00
Family_Income            5.00
Internet_Access          0.00
Study_Hours_per_Day      5.00
Attendance_Rate          0.00
Assignment_Delay_Days    0.00
Travel_Time_Minutes      0.00
Part_Time_Job            0.00
Scholarship              0.00
Stress_Index             5.00
GPA                      0.00
Semester_GPA             0.00
CGPA                     0.00
Semester                 0.00
Department               0.00
Parental_Education       5.11
Dropout                  0.00
dtype: float64

In [35]:
row_missing_pct = df.isnull().mean(axis=1) * 100

In [12]:
df.dropna(inplace = True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9020 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    9020 non-null   float64
 1   Gender                 9020 non-null   object
 2   Family_Income          9020 non-null   float64
 3   Internet_Access        9020 non-null   object
 4   Study_Hours_per_Day    9020 non-null   float64
 5   Attendance_Rate        9020 non-null   float64
 6   Assignment_Delay_Days  9020 non-null   int64
 7   Travel_Time_Minutes    9020 non-null   float64
 8   Part_Time_Job          9020 non-null   object
 9   Scholarship            9020 non-null   object
 10  Stress_Index           9020 non-null   float64
 11  GPA                    9020 non-null   float64
 12  Semester_GPA           9020 non-null   float64
 13  CGPA                   9020 non-null   float64
 14  Semester               9020 non-null   object
 15  Department             9020 non-null   object
 16  Parental_Education     9020 non-null   object
 17  Dropout                9020 non-null   int64
dtypes: float64(9), int64(2), object(7)
memory usage: 1.3+ MB

In [38]:
row_missing_pct.sort_values(ascending=False).head()

3723    22.222222
3400    22.222222
958     22.222222
5938    22.222222
6830    22.222222
dtype: float64

In [14]:
X, y = df.drop(columns = ["Dropout"]),df["Dropout"]

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
df.columns

Index(['Age', 'Gender', 'Family_Income', 'Internet_Access',
       'Study_Hours_per_Day', 'Attendance_Rate', 'Assignment_Delay_Days',
       'Travel_Time_Minutes', 'Part_Time_Job', 'Scholarship', 'Stress_Index',
       'GPA', 'Semester_GPA', 'CGPA', 'Semester', 'Department',
       'Parental_Education', 'Dropout'],
      dtype='object')

In [17]:
categorical_col = ["Gender","Internet_Access",
                   "Part_Time_Job","Scholarship","Semester",
                   "Department","Parental_Education" ]
numerical_col = ['Age',
       'Study_Hours_per_Day', 'Attendance_Rate',
       'Travel_Time_Minutes', 'Stress_Index',
       'GPA', 'Semester_GPA', 'CGPA']
skewed_col = ["Assignment_Delay_Days","Family_Income"]

In [18]:
from sklearn.preprocessing import PowerTransformer

In [19]:
skewed_pipe = Pipeline([
("power", PowerTransformer(method = "yeo-johnson"))])

cat_pipe = Pipeline([
("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

num_pipe = Pipeline([
("scaler", StandardScaler())])

In [20]:
preprocessor = ColumnTransformer([
("skew", skewed_pipe, skewed_col),
("cat", cat_pipe, categorical_col),
("num", num_pipe, numerical_col)])

#BASELINE MODEL

In [21]:
pipe_base = Pipeline([
    ("preprocessing",preprocessor),
    ("base_model",base_model)
])

In [22]:
pipe_base.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('skew',
                                                  Pipeline(steps=[('power',
                                                                   PowerTransformer())]),
                                                  ['Assignment_Delay_Days',
                                                   'Family_Income']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Gender', 'Internet_Access',
                                                   'Part_Time_Job',
                                                   'Scholarship', 'Semester',
                                                   'Department',
                                                   'Parental_Education']),
                                                 ('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['Age', 'Study_Hours_per_Day',
                                                   'Attendance_Rate',
                                                   'Travel_Time_Minutes',
                                                   'Stress_Index', 'GPA',
                                                   'Semester_GPA', 'CGPA'])])),
                ('base_model',
                 LogisticRegression(class_weight='balanced', max_iter=1000,
                                    random_state=42))])

In [23]:
y_pred_base = pipe_base.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

In [25]:
print(f"Accuracy: {accuracy_score(y_test, y_pred_base)}")
print(f"Precision : {precision_score(y_test, y_pred_base)}")
print(f"Recall : {recall_score(y_test, y_pred_base)}")
print(f"F1 Score : {f1_score(y_test, y_pred_base)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred_base)}")
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_base)
print(f"confusion matrix :\n{cm}")

Accuracy: 0.746119733924612
Precision : 0.48270676691729325
Recall : 0.7379310344827587
F1 Score : 0.5836363636363636
Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.75      0.82      1369
           1       0.48      0.74      0.58       435

    accuracy                           0.75      1804
   macro avg       0.69      0.74      0.70      1804
weighted avg       0.80      0.75      0.76      1804

confusion matrix :
[[1025  344]
 [ 114  321]]

# Logistic Regression with parameter tuning and using smote_nc

In [26]:
from imblearn.over_sampling import SMOTENC
from imblearn.pipeline import Pipeline as ImbPipeline

In [27]:
categorical_indices = [X.columns.get_loc(col) for col in categorical_col]
categorical_indices

[1, 3, 8, 9, 14, 15, 16]

In [28]:
categorical_indices = [X.columns.get_loc(col) for col in categorical_col]

smote_nc = SMOTENC(
    categorical_features=categorical_indices,
    random_state=42
)

In [29]:
logistic = LogisticRegression()

In [30]:
params = {
    "logistic__C": [0.01, 0.1, 1, 10],
    "logistic__penalty": ["l2"],
    "logistic__solver": ["lbfgs"],
    "logistic__max_iter": [500,1000]
}

In [40]:
pipe_logistic = ImbPipeline([
    ("preprocessing",preprocessor),
    ("smote",smote_nc),
    ("logistic",logistic)
])

In [41]:
from sklearn.model_selection import GridSearchCV

In [42]:
grid = GridSearchCV(
    pipe_logistic,
    params,
    cv = 10,
    scoring = "f1",
    n_jobs = -1,
    verbose = 1
)

In [43]:
grid.fit(X_train, y_train)

Fitting 10 folds for each of 8 candidates, totalling 80 fits

GridSearchCV(cv=10,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(transformers=[('skew',
                                                                         Pipeline(steps=[('power',
                                                                                          PowerTransformer())]),
                                                                         ['Assignment_Delay_Days',
                                                                          'Family_Income']),
                                                                        ('cat',
                                                                         Pipeline(steps=[('encoder',
                                                                                          OneHotEncoder(handle_unknown='ignore',
                                                                                                        sparse_output=False))]),
                                                                         ['Gender',
                                                                          'Internet_Access',
                                                                          'Part_Time_Job',
                                                                          'Scholarship',
                                                                          'Sem...
                                                                          'Attendance_Rate',
                                                                          'Travel_Time_Minutes',
                                                                          'Stress_Index',
                                                                          'GPA',
                                                                          'Semester_GPA',
                                                                          'CGPA'])])),
                                       ('smote',
                                        SMOTENC(categorical_features=[1, 3, 8,
                                                                      9, 14, 15,
                                                                      16],
                                                random_state=42)),
                                       ('logistic', LogisticRegression())]),
             n_jobs=-1,
             param_grid={'logistic__C': [0.01, 0.1, 1, 10],
                         'logistic__max_iter': [500, 1000],
                         'logistic__penalty': ['l2'],
                         'logistic__solver': ['lbfgs']},
             scoring='f1', verbose=1)

In [44]:
y_pred_logistic = grid.predict(X_test)

In [45]:
print(f"Accuracy: {accuracy_score(y_test, y_pred_logistic)}")
print(f"Precision : {precision_score(y_test, y_pred_logistic)}")
print(f"Recall : {recall_score(y_test, y_pred_logistic)}")
print(f"F1 Score : {f1_score(y_test, y_pred_logistic)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred_logistic)}")
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_logistic)
print(f"confusion matrix :\n{cm}")

Accuracy: 0.7788248337028825
Precision : 0.5340909090909091
Recall : 0.6482758620689655
F1 Score : 0.5856697819314641
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.82      0.85      1369
           1       0.53      0.65      0.59       435

    accuracy                           0.78      1804
   macro avg       0.71      0.73      0.72      1804
weighted avg       0.80      0.78      0.79      1804

confusion matrix :
[[1123  246]
 [ 153  282]]

# RandomForestClassifier

In [46]:
from sklearn.ensemble import RandomForestClassifier

In [47]:
rfc = RandomForestClassifier(
    random_state=42,
    bootstrap=True,
    oob_score=True
)

In [48]:
preprocessor_tree = ColumnTransformer([
("skew", skewed_pipe, skewed_col),
("cat", cat_pipe, categorical_col),
])

In [49]:
preprocessor_tree = ColumnTransformer([
("skew", skewed_pipe, skewed_col),
("cat", cat_pipe, categorical_col),
])

In [50]:
pipeline_rfc = ImbPipeline([
("preprocessing", preprocessor_tree),
("somte", smote_nc),
("rfc", rfc)
])

In [51]:
params_random = {
    "rfc__n_estimators": [200, 400, 600],
    "rfc__max_depth": [None, 10, 20, 30],
    "rfc__min_samples_split": [2, 5, 10],
    "rfc__min_samples_leaf": [1, 2, 4]
}

In [52]:
from sklearn.model_selection import RandomizedSearchCV
random_search = RandomizedSearchCV(
    pipeline_rfc,
    param_distributions=params_random,
    n_iter=30,
    cv=5,
    scoring="f1",
    n_jobs=-1,
    random_state=42
)

In [53]:
random_search.fit(X_train, y_train)

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessing',
                                              ColumnTransformer(transformers=[('skew',
                                                                               Pipeline(steps=[('power',
                                                                                                PowerTransformer())]),
                                                                               ['Assignment_Delay_Days',
                                                                                'Family_Income']),
                                                                              ('cat',
                                                                               Pipeline(steps=[('encoder',
                                                                                                OneHotEncoder(handle_unknown='ignore',
                                                                                                              sparse_output=False))]),
                                                                               ['Gender',
                                                                                'Internet_Access',
                                                                                'Part_Time_Job',
                                                                                'Scholarship'...
                                                                                'Parental_Education'])])),
                                             ('somte',
                                              SMOTENC(categorical_features=[1,
                                                                            3,
                                                                            8,
                                                                            9,
                                                                            14,
                                                                            15,
                                                                            16],
                                                      random_state=42)),
                                             ('rfc',
                                              RandomForestClassifier(oob_score=True,
                                                                     random_state=42))]),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'rfc__max_depth': [None, 10, 20, 30],
                                        'rfc__min_samples_leaf': [1, 2, 4],
                                        'rfc__min_samples_split': [2, 5, 10],
                                        'rfc__n_estimators': [200, 400, 600]},
                   random_state=42, scoring='f1')

In [54]:
random_search.best_params_

{'rfc__n_estimators': 200,
 'rfc__min_samples_split': 2,
 'rfc__min_samples_leaf': 4,
 'rfc__max_depth': 10}

In [55]:
best_rfc = random_search.best_estimator_

In [56]:
y_pred_rfc = best_rfc.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred_rfc)}")
print(f"Precision : {precision_score(y_test, y_pred_rfc)}")
print(f"Recall : {recall_score(y_test, y_pred_rfc)}")
print(f"F1 Score : {f1_score(y_test, y_pred_rfc)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred_rfc)}")
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_rfc)
print(f"confusion matrix :\n{cm}")

Accuracy: 0.6468957871396895
Precision : 0.24494949494949494
Recall : 0.22298850574712645
F1 Score : 0.23345367027677497
Classification Report:
              precision    recall  f1-score   support

           0       0.76      0.78      0.77      1369
           1       0.24      0.22      0.23       435

    accuracy                           0.65      1804
   macro avg       0.50      0.50      0.50      1804
weighted avg       0.64      0.65      0.64      1804

confusion matrix :
[[1070  299]
 [ 338   97]]

# GradientBoostingClassifier

In [57]:
from sklearn.ensemble import GradientBoostingClassifier
from scipy.stats import randint, uniform
param_dist_gb = {
    "gbc__n_estimators": randint(150, 400),

    "gbc__learning_rate": uniform(0.01, 0.08),  # smaller range

    "gbc__max_depth": randint(3, 6),  # avoid deep trees

    "gbc__min_samples_split": randint(5, 15),  # avoid very small splits

    "gbc__min_samples_leaf": randint(2, 6),  # avoid 1 (unstable)

    "gbc__subsample": uniform(0.7, 0.3),  # 0.7 to 1.0 (safer)

    "gbc__max_features": ["sqrt", "log2"]  # remove None (unstable)
}

In [58]:
gbc = GradientBoostingClassifier(random_state=42)

In [59]:
pipe_gbc = ImbPipeline([
    ("preprocessing",preprocessor_tree),
    ("smote", smote_nc),
    ("gbc",gbc)])

In [60]:
from sklearn.model_selection import RandomizedSearchCV

random_gb = RandomizedSearchCV(
    pipe_gbc,
    param_distributions=param_dist_gb,
    n_iter=50,
    cv=5,
    scoring="f1",
    n_jobs=-1,
    random_state=42,
    verbose=2,
    error_score = 0
)

In [61]:
random_gb.fit(X_train, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits

RandomizedSearchCV(cv=5, error_score=0,
                   estimator=Pipeline(steps=[('preprocessing',
                                              ColumnTransformer(transformers=[('skew',
                                                                               Pipeline(steps=[('power',
                                                                                                PowerTransformer())]),
                                                                               ['Assignment_Delay_Days',
                                                                                'Family_Income']),
                                                                              ('cat',
                                                                               Pipeline(steps=[('encoder',
                                                                                                OneHotEncoder(handle_unknown='ignore',
                                                                                                              sparse_output=False))]),
                                                                               ['Gender',
                                                                                'Internet_Access',
                                                                                'Part_Time_Job'...
                                        'gbc__min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7fd0de33a8d0>,
                                        'gbc__min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7fd0de3265a0>,
                                        'gbc__n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7fd0de257ec0>,
                                        'gbc__subsample': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x7fd0de258050>},
                   random_state=42, scoring='f1', verbose=2)

In [62]:
random_gb.best_params_

{'gbc__learning_rate': np.float64(0.010062301267281146),
 'gbc__max_depth': 3,
 'gbc__max_features': 'sqrt',
 'gbc__min_samples_leaf': 5,
 'gbc__min_samples_split': 14,
 'gbc__n_estimators': 171,
 'gbc__subsample': np.float64(0.7021198915659151)}

In [63]:
random_gb.best_score_

np.float64(0.29115961741920066)

In [64]:
best_gbc = random_gb.best_estimator_
y_pred_gbc = best_gbc.predict(X_test)
from sklearn.metrics import precision_score, recall_score, f1_score
print(f"Accuracy: {accuracy_score(y_test, y_pred_gbc)}")
print(f"Precision : {precision_score(y_test, y_pred_gbc)}")
print(f"Recall : {recall_score(y_test, y_pred_gbc)}")
print(f"F1 Score : {f1_score(y_test, y_pred_gbc)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred_gbc)}")
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_gbc)
print(f"confusion matrix :\n{cm}")

Accuracy: 0.5914634146341463
Precision : 0.26257861635220126
Recall : 0.3839080459770115
F1 Score : 0.3118580765639589
Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.66      0.71      1369
           1       0.26      0.38      0.31       435

    accuracy                           0.59      1804
   macro avg       0.52      0.52      0.51      1804
weighted avg       0.65      0.59      0.61      1804

confusion matrix :
[[900 469]
 [268 167]]

# XgBoostingClassifier

In [65]:
from scipy.stats import randint, uniform

param_dist_xgb = {
    "xgb__n_estimators": randint(200, 600),

    "xgb__learning_rate": uniform(0.01, 0.09),

    "xgb__max_depth": randint(3, 6),

    "xgb__subsample": uniform(0.75, 0.25),

    "xgb__colsample_bytree": uniform(0.7, 0.3),

    "xgb__gamma": uniform(0, 2),

    "xgb__min_child_weight": randint(2, 8),

    "xgb__reg_lambda": uniform(0.5, 1.5)
}

In [66]:
from xgboost import XGBClassifier

In [67]:
xgb = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    use_label_encoder=False,
    random_state=42,
    n_jobs=-1
)

In [68]:
pipe_xgb = ImbPipeline([
    ("preprocessing", preprocessor_tree),
    ("smote", smote_nc),
    ("xgb", xgb)
])

In [69]:
random_xgb = RandomizedSearchCV(
    pipe_xgb,
    param_distributions=param_dist_xgb,
    n_iter=50,
    cv=5,
    scoring="f1",
    n_jobs= 1,
    random_state=42,
    verbose=2,
    error_score = 0
)

In [ ]:
random_xgb.fit(X_train, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:37:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8123620356542087, xgb__gamma=1.9014286128198323, xgb__learning_rate=0.07587945476302645, xgb__max_depth=3, xgb__min_child_weight=6, xgb__n_estimators=302, xgb__reg_lambda=1.1687491292803867, xgb__subsample=0.7749937289545007; total time=   2.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:37:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8123620356542087, xgb__gamma=1.9014286128198323, xgb__learning_rate=0.07587945476302645, xgb__max_depth=3, xgb__min_child_weight=6, xgb__n_estimators=302, xgb__reg_lambda=1.1687491292803867, xgb__subsample=0.7749937289545007; total time=   2.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:37:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8123620356542087, xgb__gamma=1.9014286128198323, xgb__learning_rate=0.07587945476302645, xgb__max_depth=3, xgb__min_child_weight=6, xgb__n_estimators=302, xgb__reg_lambda=1.1687491292803867, xgb__subsample=0.7749937289545007; total time=   2.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:37:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8123620356542087, xgb__gamma=1.9014286128198323, xgb__learning_rate=0.07587945476302645, xgb__max_depth=3, xgb__min_child_weight=6, xgb__n_estimators=302, xgb__reg_lambda=1.1687491292803867, xgb__subsample=0.7749937289545007; total time=   2.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:37:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8123620356542087, xgb__gamma=1.9014286128198323, xgb__learning_rate=0.07587945476302645, xgb__max_depth=3, xgb__min_child_weight=6, xgb__n_estimators=302, xgb__reg_lambda=1.1687491292803867, xgb__subsample=0.7749937289545007; total time=   3.8s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:37:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8377746675897602, xgb__gamma=0.6674172222780437, xgb__learning_rate=0.022858013612974667, xgb__max_depth=5, xgb__min_child_weight=7, xgb__n_estimators=508, xgb__reg_lambda=1.9548647782429915, xgb__subsample=0.9581106602001055; total time=   2.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:37:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8377746675897602, xgb__gamma=0.6674172222780437, xgb__learning_rate=0.022858013612974667, xgb__max_depth=5, xgb__min_child_weight=7, xgb__n_estimators=508, xgb__reg_lambda=1.9548647782429915, xgb__subsample=0.9581106602001055; total time=   2.8s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:37:53] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8377746675897602, xgb__gamma=0.6674172222780437, xgb__learning_rate=0.022858013612974667, xgb__max_depth=5, xgb__min_child_weight=7, xgb__n_estimators=508, xgb__reg_lambda=1.9548647782429915, xgb__subsample=0.9581106602001055; total time=   3.1s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:37:56] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8377746675897602, xgb__gamma=0.6674172222780437, xgb__learning_rate=0.022858013612974667, xgb__max_depth=5, xgb__min_child_weight=7, xgb__n_estimators=508, xgb__reg_lambda=1.9548647782429915, xgb__subsample=0.9581106602001055; total time=   4.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:00] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8377746675897602, xgb__gamma=0.6674172222780437, xgb__learning_rate=0.022858013612974667, xgb__max_depth=5, xgb__min_child_weight=7, xgb__n_estimators=508, xgb__reg_lambda=1.9548647782429915, xgb__subsample=0.9581106602001055; total time=   2.8s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7637017332034828, xgb__gamma=0.36364993441420124, xgb__learning_rate=0.026506405886809047, xgb__max_depth=4, xgb__min_child_weight=7, xgb__n_estimators=452, xgb__reg_lambda=1.1479175279631737, xgb__subsample=0.8228072850495105; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7637017332034828, xgb__gamma=0.36364993441420124, xgb__learning_rate=0.026506405886809047, xgb__max_depth=4, xgb__min_child_weight=7, xgb__n_estimators=452, xgb__reg_lambda=1.1479175279631737, xgb__subsample=0.8228072850495105; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:09] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7637017332034828, xgb__gamma=0.36364993441420124, xgb__learning_rate=0.026506405886809047, xgb__max_depth=4, xgb__min_child_weight=7, xgb__n_estimators=452, xgb__reg_lambda=1.1479175279631737, xgb__subsample=0.8228072850495105; total time=   4.8s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7637017332034828, xgb__gamma=0.36364993441420124, xgb__learning_rate=0.026506405886809047, xgb__max_depth=4, xgb__min_child_weight=7, xgb__n_estimators=452, xgb__reg_lambda=1.1479175279631737, xgb__subsample=0.8228072850495105; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7637017332034828, xgb__gamma=0.36364993441420124, xgb__learning_rate=0.026506405886809047, xgb__max_depth=4, xgb__min_child_weight=7, xgb__n_estimators=452, xgb__reg_lambda=1.1479175279631737, xgb__subsample=0.8228072850495105; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8835558684167137, xgb__gamma=0.27898772130408367, xgb__learning_rate=0.03629301836816963, xgb__max_depth=5, xgb__min_child_weight=7, xgb__n_estimators=374, xgb__reg_lambda=1.427579013999631, xgb__subsample=0.8456154978167907; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8835558684167137, xgb__gamma=0.27898772130408367, xgb__learning_rate=0.03629301836816963, xgb__max_depth=5, xgb__min_child_weight=7, xgb__n_estimators=374, xgb__reg_lambda=1.427579013999631, xgb__subsample=0.8456154978167907; total time=   4.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8835558684167137, xgb__gamma=0.27898772130408367, xgb__learning_rate=0.03629301836816963, xgb__max_depth=5, xgb__min_child_weight=7, xgb__n_estimators=374, xgb__reg_lambda=1.427579013999631, xgb__subsample=0.8456154978167907; total time=   2.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8835558684167137, xgb__gamma=0.27898772130408367, xgb__learning_rate=0.03629301836816963, xgb__max_depth=5, xgb__min_child_weight=7, xgb__n_estimators=374, xgb__reg_lambda=1.427579013999631, xgb__subsample=0.8456154978167907; total time=   2.7s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:31] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8835558684167137, xgb__gamma=0.27898772130408367, xgb__learning_rate=0.03629301836816963, xgb__max_depth=5, xgb__min_child_weight=7, xgb__n_estimators=374, xgb__reg_lambda=1.427579013999631, xgb__subsample=0.8456154978167907; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9949692657420364, xgb__gamma=0.9335257864959599, xgb__learning_rate=0.08739463660626884, xgb__max_depth=5, xgb__min_child_weight=6, xgb__n_estimators=528, xgb__reg_lambda=0.5975773894779193, xgb__subsample=0.9872213843133333; total time=   2.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9949692657420364, xgb__gamma=0.9335257864959599, xgb__learning_rate=0.08739463660626884, xgb__max_depth=5, xgb__min_child_weight=6, xgb__n_estimators=528, xgb__reg_lambda=0.5975773894779193, xgb__subsample=0.9872213843133333; total time=   3.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9949692657420364, xgb__gamma=0.9335257864959599, xgb__learning_rate=0.08739463660626884, xgb__max_depth=5, xgb__min_child_weight=6, xgb__n_estimators=528, xgb__reg_lambda=0.5975773894779193, xgb__subsample=0.9872213843133333; total time=   2.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:42] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9949692657420364, xgb__gamma=0.9335257864959599, xgb__learning_rate=0.08739463660626884, xgb__max_depth=5, xgb__min_child_weight=6, xgb__n_estimators=528, xgb__reg_lambda=0.5975773894779193, xgb__subsample=0.9872213843133333; total time=   2.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9949692657420364, xgb__gamma=0.9335257864959599, xgb__learning_rate=0.08739463660626884, xgb__max_depth=5, xgb__min_child_weight=6, xgb__n_estimators=528, xgb__reg_lambda=0.5975773894779193, xgb__subsample=0.9872213843133333; total time=   2.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9896896099223678, xgb__gamma=1.6167946962329223, xgb__learning_rate=0.03741523922560336, xgb__max_depth=3, xgb__min_child_weight=3, xgb__n_estimators=539, xgb__reg_lambda=0.8615381990390176, xgb__subsample=0.9208158797063646; total time=   2.8s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:51] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9896896099223678, xgb__gamma=1.6167946962329223, xgb__learning_rate=0.03741523922560336, xgb__max_depth=3, xgb__min_child_weight=3, xgb__n_estimators=539, xgb__reg_lambda=0.8615381990390176, xgb__subsample=0.9208158797063646; total time=   3.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:54] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9896896099223678, xgb__gamma=1.6167946962329223, xgb__learning_rate=0.03741523922560336, xgb__max_depth=3, xgb__min_child_weight=3, xgb__n_estimators=539, xgb__reg_lambda=0.8615381990390176, xgb__subsample=0.9208158797063646; total time=   2.7s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:56] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9896896099223678, xgb__gamma=1.6167946962329223, xgb__learning_rate=0.03741523922560336, xgb__max_depth=3, xgb__min_child_weight=3, xgb__n_estimators=539, xgb__reg_lambda=0.8615381990390176, xgb__subsample=0.9208158797063646; total time=   2.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:38:59] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9896896099223678, xgb__gamma=1.6167946962329223, xgb__learning_rate=0.03741523922560336, xgb__max_depth=3, xgb__min_child_weight=3, xgb__n_estimators=539, xgb__reg_lambda=0.8615381990390176, xgb__subsample=0.9208158797063646; total time=   2.8s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8829989973347863, xgb__gamma=1.6663898234723287, xgb__learning_rate=0.025602818815699487, xgb__max_depth=3, xgb__min_child_weight=5, xgb__n_estimators=249, xgb__reg_lambda=1.4937834265309728, xgb__subsample=0.8279277690223528; total time=   3.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8829989973347863, xgb__gamma=1.6663898234723287, xgb__learning_rate=0.025602818815699487, xgb__max_depth=3, xgb__min_child_weight=5, xgb__n_estimators=249, xgb__reg_lambda=1.4937834265309728, xgb__subsample=0.8279277690223528; total time=   2.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8829989973347863, xgb__gamma=1.6663898234723287, xgb__learning_rate=0.025602818815699487, xgb__max_depth=3, xgb__min_child_weight=5, xgb__n_estimators=249, xgb__reg_lambda=1.4937834265309728, xgb__subsample=0.8279277690223528; total time=   2.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8829989973347863, xgb__gamma=1.6663898234723287, xgb__learning_rate=0.025602818815699487, xgb__max_depth=3, xgb__min_child_weight=5, xgb__n_estimators=249, xgb__reg_lambda=1.4937834265309728, xgb__subsample=0.8279277690223528; total time=   2.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8829989973347863, xgb__gamma=1.6663898234723287, xgb__learning_rate=0.025602818815699487, xgb__max_depth=3, xgb__min_child_weight=5, xgb__n_estimators=249, xgb__reg_lambda=1.4937834265309728, xgb__subsample=0.8279277690223528; total time=   2.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8560204063533432, xgb__gamma=1.0934205586865593, xgb__learning_rate=0.02663690099729743, xgb__max_depth=5, xgb__min_child_weight=3, xgb__n_estimators=417, xgb__reg_lambda=1.1746312000546486, xgb__subsample=0.8487875590004537; total time=   4.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8560204063533432, xgb__gamma=1.0934205586865593, xgb__learning_rate=0.02663690099729743, xgb__max_depth=5, xgb__min_child_weight=3, xgb__n_estimators=417, xgb__reg_lambda=1.1746312000546486, xgb__subsample=0.8487875590004537; total time=   2.7s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8560204063533432, xgb__gamma=1.0934205586865593, xgb__learning_rate=0.02663690099729743, xgb__max_depth=5, xgb__min_child_weight=3, xgb__n_estimators=417, xgb__reg_lambda=1.1746312000546486, xgb__subsample=0.8487875590004537; total time=   2.8s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8560204063533432, xgb__gamma=1.0934205586865593, xgb__learning_rate=0.02663690099729743, xgb__max_depth=5, xgb__min_child_weight=3, xgb__n_estimators=417, xgb__reg_lambda=1.1746312000546486, xgb__subsample=0.8487875590004537; total time=   2.7s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8560204063533432, xgb__gamma=1.0934205586865593, xgb__learning_rate=0.02663690099729743, xgb__max_depth=5, xgb__min_child_weight=3, xgb__n_estimators=417, xgb__reg_lambda=1.1746312000546486, xgb__subsample=0.8487875590004537; total time=   4.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:31] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9779976597381381, xgb__gamma=1.4545439917128418, xgb__learning_rate=0.039388669192525184, xgb__max_depth=4, xgb__min_child_weight=5, xgb__n_estimators=389, xgb__reg_lambda=0.9879954961448965, xgb__subsample=0.8471693224223705; total time=   2.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9779976597381381, xgb__gamma=1.4545439917128418, xgb__learning_rate=0.039388669192525184, xgb__max_depth=4, xgb__min_child_weight=5, xgb__n_estimators=389, xgb__reg_lambda=0.9879954961448965, xgb__subsample=0.8471693224223705; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9779976597381381, xgb__gamma=1.4545439917128418, xgb__learning_rate=0.039388669192525184, xgb__max_depth=4, xgb__min_child_weight=5, xgb__n_estimators=389, xgb__reg_lambda=0.9879954961448965, xgb__subsample=0.8471693224223705; total time=   2.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9779976597381381, xgb__gamma=1.4545439917128418, xgb__learning_rate=0.039388669192525184, xgb__max_depth=4, xgb__min_child_weight=5, xgb__n_estimators=389, xgb__reg_lambda=0.9879954961448965, xgb__subsample=0.8471693224223705; total time=   4.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9779976597381381, xgb__gamma=1.4545439917128418, xgb__learning_rate=0.039388669192525184, xgb__max_depth=4, xgb__min_child_weight=5, xgb__n_estimators=389, xgb__reg_lambda=0.9879954961448965, xgb__subsample=0.8471693224223705; total time=   2.7s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:46] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7814047095321688, xgb__gamma=1.6574750183038587, xgb__learning_rate=0.042107799402423034, xgb__max_depth=3, xgb__min_child_weight=2, xgb__n_estimators=356, xgb__reg_lambda=1.7032954711310595, xgb__subsample=0.7686376609199427; total time=   2.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7814047095321688, xgb__gamma=1.6574750183038587, xgb__learning_rate=0.042107799402423034, xgb__max_depth=3, xgb__min_child_weight=2, xgb__n_estimators=356, xgb__reg_lambda=1.7032954711310595, xgb__subsample=0.7686376609199427; total time=   2.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:51] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7814047095321688, xgb__gamma=1.6574750183038587, xgb__learning_rate=0.042107799402423034, xgb__max_depth=3, xgb__min_child_weight=2, xgb__n_estimators=356, xgb__reg_lambda=1.7032954711310595, xgb__subsample=0.7686376609199427; total time=   2.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:54] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7814047095321688, xgb__gamma=1.6574750183038587, xgb__learning_rate=0.042107799402423034, xgb__max_depth=3, xgb__min_child_weight=2, xgb__n_estimators=356, xgb__reg_lambda=1.7032954711310595, xgb__subsample=0.7686376609199427; total time=   3.8s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:57] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7814047095321688, xgb__gamma=1.6574750183038587, xgb__learning_rate=0.042107799402423034, xgb__max_depth=3, xgb__min_child_weight=2, xgb__n_estimators=356, xgb__reg_lambda=1.7032954711310595, xgb__subsample=0.7686376609199427; total time=   2.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:39:59] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9960660809801551, xgb__gamma=1.5444895385933148, xgb__learning_rate=0.027884411338075517, xgb__max_depth=5, xgb__min_child_weight=4, xgb__n_estimators=280, xgb__reg_lambda=1.567012929122975, xgb__subsample=0.9475438851328014; total time=   2.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9960660809801551, xgb__gamma=1.5444895385933148, xgb__learning_rate=0.027884411338075517, xgb__max_depth=5, xgb__min_child_weight=4, xgb__n_estimators=280, xgb__reg_lambda=1.567012929122975, xgb__subsample=0.9475438851328014; total time=   2.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9960660809801551, xgb__gamma=1.5444895385933148, xgb__learning_rate=0.027884411338075517, xgb__max_depth=5, xgb__min_child_weight=4, xgb__n_estimators=280, xgb__reg_lambda=1.567012929122975, xgb__subsample=0.9475438851328014; total time=   2.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:08] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9960660809801551, xgb__gamma=1.5444895385933148, xgb__learning_rate=0.027884411338075517, xgb__max_depth=5, xgb__min_child_weight=4, xgb__n_estimators=280, xgb__reg_lambda=1.567012929122975, xgb__subsample=0.9475438851328014; total time=   3.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9960660809801551, xgb__gamma=1.5444895385933148, xgb__learning_rate=0.027884411338075517, xgb__max_depth=5, xgb__min_child_weight=4, xgb__n_estimators=280, xgb__reg_lambda=1.567012929122975, xgb__subsample=0.9475438851328014; total time=   2.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8817879924343034, xgb__gamma=1.852601757026698, xgb__learning_rate=0.068596932295175, xgb__max_depth=5, xgb__min_child_weight=2, xgb__n_estimators=527, xgb__reg_lambda=1.174176011207305, xgb__subsample=0.7738525291226028; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8817879924343034, xgb__gamma=1.852601757026698, xgb__learning_rate=0.068596932295175, xgb__max_depth=5, xgb__min_child_weight=2, xgb__n_estimators=527, xgb__reg_lambda=1.174176011207305, xgb__subsample=0.7738525291226028; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8817879924343034, xgb__gamma=1.852601757026698, xgb__learning_rate=0.068596932295175, xgb__max_depth=5, xgb__min_child_weight=2, xgb__n_estimators=527, xgb__reg_lambda=1.174176011207305, xgb__subsample=0.7738525291226028; total time=   4.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8817879924343034, xgb__gamma=1.852601757026698, xgb__learning_rate=0.068596932295175, xgb__max_depth=5, xgb__min_child_weight=2, xgb__n_estimators=527, xgb__reg_lambda=1.174176011207305, xgb__subsample=0.7738525291226028; total time=   2.7s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8817879924343034, xgb__gamma=1.852601757026698, xgb__learning_rate=0.068596932295175, xgb__max_depth=5, xgb__min_child_weight=2, xgb__n_estimators=527, xgb__reg_lambda=1.174176011207305, xgb__subsample=0.7738525291226028; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8112454756594799, xgb__gamma=1.3376825053272146, xgb__learning_rate=0.06993301209557469, xgb__max_depth=4, xgb__min_child_weight=4, xgb__n_estimators=234, xgb__reg_lambda=1.2083223877429239, xgb__subsample=0.7798985614845755; total time=   2.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8112454756594799, xgb__gamma=1.3376825053272146, xgb__learning_rate=0.06993301209557469, xgb__max_depth=4, xgb__min_child_weight=4, xgb__n_estimators=234, xgb__reg_lambda=1.2083223877429239, xgb__subsample=0.7798985614845755; total time=   2.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8112454756594799, xgb__gamma=1.3376825053272146, xgb__learning_rate=0.06993301209557469, xgb__max_depth=4, xgb__min_child_weight=4, xgb__n_estimators=234, xgb__reg_lambda=1.2083223877429239, xgb__subsample=0.7798985614845755; total time=   3.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8112454756594799, xgb__gamma=1.3376825053272146, xgb__learning_rate=0.06993301209557469, xgb__max_depth=4, xgb__min_child_weight=4, xgb__n_estimators=234, xgb__reg_lambda=1.2083223877429239, xgb__subsample=0.7798985614845755; total time=   2.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8112454756594799, xgb__gamma=1.3376825053272146, xgb__learning_rate=0.06993301209557469, xgb__max_depth=4, xgb__min_child_weight=4, xgb__n_estimators=234, xgb__reg_lambda=1.2083223877429239, xgb__subsample=0.7798985614845755; total time=   2.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9139734361668984, xgb__gamma=1.5215700972337949, xgb__learning_rate=0.06051494778125466, xgb__max_depth=5, xgb__min_child_weight=7, xgb__n_estimators=558, xgb__reg_lambda=0.560650384307647, xgb__subsample=0.9276657224214468; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9139734361668984, xgb__gamma=1.5215700972337949, xgb__learning_rate=0.06051494778125466, xgb__max_depth=5, xgb__min_child_weight=7, xgb__n_estimators=558, xgb__reg_lambda=0.560650384307647, xgb__subsample=0.9276657224214468; total time=   4.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9139734361668984, xgb__gamma=1.5215700972337949, xgb__learning_rate=0.06051494778125466, xgb__max_depth=5, xgb__min_child_weight=7, xgb__n_estimators=558, xgb__reg_lambda=0.560650384307647, xgb__subsample=0.9276657224214468; total time=   2.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9139734361668984, xgb__gamma=1.5215700972337949, xgb__learning_rate=0.06051494778125466, xgb__max_depth=5, xgb__min_child_weight=7, xgb__n_estimators=558, xgb__reg_lambda=0.560650384307647, xgb__subsample=0.9276657224214468; total time=   2.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:53] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.9139734361668984, xgb__gamma=1.5215700972337949, xgb__learning_rate=0.06051494778125466, xgb__max_depth=5, xgb__min_child_weight=7, xgb__n_estimators=558, xgb__reg_lambda=0.560650384307647, xgb__subsample=0.9276657224214468; total time=   2.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:55] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7332672462435493, xgb__gamma=0.8786730037315402, xgb__learning_rate=0.028154728210185657, xgb__max_depth=5, xgb__min_child_weight=2, xgb__n_estimators=251, xgb__reg_lambda=1.3449133579645756, xgb__subsample=0.9238790216065319; total time=   2.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:40:59] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7332672462435493, xgb__gamma=0.8786730037315402, xgb__learning_rate=0.028154728210185657, xgb__max_depth=5, xgb__min_child_weight=2, xgb__n_estimators=251, xgb__reg_lambda=1.3449133579645756, xgb__subsample=0.9238790216065319; total time=   3.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:41:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7332672462435493, xgb__gamma=0.8786730037315402, xgb__learning_rate=0.028154728210185657, xgb__max_depth=5, xgb__min_child_weight=2, xgb__n_estimators=251, xgb__reg_lambda=1.3449133579645756, xgb__subsample=0.9238790216065319; total time=   2.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:41:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7332672462435493, xgb__gamma=0.8786730037315402, xgb__learning_rate=0.028154728210185657, xgb__max_depth=5, xgb__min_child_weight=2, xgb__n_estimators=251, xgb__reg_lambda=1.3449133579645756, xgb__subsample=0.9238790216065319; total time=   2.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:41:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7332672462435493, xgb__gamma=0.8786730037315402, xgb__learning_rate=0.028154728210185657, xgb__max_depth=5, xgb__min_child_weight=2, xgb__n_estimators=251, xgb__reg_lambda=1.3449133579645756, xgb__subsample=0.9238790216065319; total time=   2.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:41:09] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7417994363217627, xgb__gamma=1.2088347585556345, xgb__learning_rate=0.05858569821715058, xgb__max_depth=3, xgb__min_child_weight=5, xgb__n_estimators=212, xgb__reg_lambda=0.6154698647431895, xgb__subsample=0.822437863228442; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:41:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7417994363217627, xgb__gamma=1.2088347585556345, xgb__learning_rate=0.05858569821715058, xgb__max_depth=3, xgb__min_child_weight=5, xgb__n_estimators=212, xgb__reg_lambda=0.6154698647431895, xgb__subsample=0.822437863228442; total time=   3.0s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:41:14] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7417994363217627, xgb__gamma=1.2088347585556345, xgb__learning_rate=0.05858569821715058, xgb__max_depth=3, xgb__min_child_weight=5, xgb__n_estimators=212, xgb__reg_lambda=0.6154698647431895, xgb__subsample=0.822437863228442; total time=   2.3s

In [ ]:
random_xgb.best_params_

In [ ]:
best_xgb = random_xgb.best_estimator_

In [ ]:
y_pred_xgb = best_xgb.predict(X_test)

In [ ]:
print(f"Accuracy: {accuracy_score(y_test, y_pred_xgb)}")
print(f"Precision : {precision_score(y_test, y_pred_xgb)}")
print(f"Recall : {recall_score(y_test, y_pred_xgb)}")
print(f"F1 Score : {f1_score(y_test, y_pred_xgb)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred_xgb)}")
cm = confusion_matrix(y_test, y_pred_xgb)
print(f"confusion matrix :\n{cm}")

# BEST MODEL

## The base model (logistic regression)

In [ ]:
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# Probability for positive class ("Active")
y_proba = pipe_base.predict_proba(X_test)[:, 1]

fpr, tpr, thresholds = roc_curve(y_test, y_proba)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.3f}")
plt.plot([0, 1], [0, 1], linestyle="--")  # random line

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate (Recall)")
plt.title("ROC Curve")
plt.legend()

plot_filename = "ROC-Curve.png"
plt.savefig(plot_filename)

from google.colab import files
files.download(plot_filename)

plt.show()

In [ ]:
from sklearn.metrics import precision_recall_curve

precision, recall, thresholds = precision_recall_curve(
    y_test,
    y_proba,
)

plt.figure()
plt.plot(recall, precision)

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")

plot_filename = "Precision-Recall-Curve.png"
plt.savefig(plot_filename)

from google.colab import files
files.download(plot_filename)

plt.show()

In [ ]:
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted label")
plt.ylabel("Actual label")
plt.title("Confusion Matrix")

# Save the plot to a file
plot_filename = "confusion_matrix.png"
plt.savefig(plot_filename)

# Download the saved plot
from google.colab import files
files.download(plot_filename)

plt.show()

In [ ]:
import joblib

In [ ]:
joblib.dump(pipe_base, "model.pkl")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
joblib.dump(pipe_base, "/content/drive/MyDrive/model.pkl")

In [ ]:
from google.colab import files
files.download("/content/drive/MyDrive/model.pkl")